config/routes.rb
Rails.application.routes.draw do
  get 'home_page/index'

  resources :posts

  root 'home_page#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_page_controller.rb
class HomePageController < ApplicationController
  def index
    @posts = Post.all
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    def new
    end

    def edit
        @post = Post.find(params[:id])
    end

    def create
        @post = Post.new(post_params)
        
        @post.save
        redirect_to @post
    end

    def update
        @post = Post.find(params[:id])

        if @post.update(post_params)
            redirect_to @post
        else
            render 'edit'
        end
    end
    
    def show
        @post = Post.find(params[:id])
    end

    def destroy
        @post = Post.find(params[:id])
        @post.destroy
        
        redirect_to '/'
    end

    private
    def post_params
      params.require(:post).permit(:title, :text)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_page_helper.rb
module HomePageHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/topissimo_helper.rb
module TopissimoHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/home_page/index.html.erb
<h1 style="text-align: center">
    Blog Mesmo
</h1>

<%= link_to 'New Post', new_post_path %>

<% @posts.each do |post| %>
  <p><%= post.title %></p>
  <p><%= post.text %></p>
  <p><%= link_to 'Show', post_path(post), controller: 'posts' %></p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<h1 align="left">New Post</h1>

<%= form_with scope: :post, url: posts_path,  local: true do |form| %>

  <%= form.label :title, "Title", class: "control-label" %>
  <%= form.text_field :title, class: "form-control" %>
  <br/><br/>
  <%= form.label :text, "Text" %>
  <%= form.text_area :text %>
  <br/><br/>
  <%= form.submit "Submit" %>
<% end %>

<%= link_to 'Home', home_page_index_path %>

app/views/posts/edit.html.erb
<%= render 'form' %>

app/views/posts/new.html.erb
<h1 align="left">New Post</h1>

<%= form_with scope: :post, url: posts_path,  local: true do |form| %>

  <%= form.label :title, "Title", class: "control-label" %>
  <%= form.text_field :title, class: "form-control" %>
  <br/><br/>
  <%= form.label :text, "Text" %>
  <%= form.text_area :text %>
  <br/><br/>
  <%= form.submit "Submit" %>
<% end %>

<%= link_to 'Home', home_page_index_path %>

app/views/posts/show.html.erb
<h2><%= @post.title %></h2><br>
<p><%= @post.text %></p>

<%= link_to 'Edit', edit_post_path(@post) %>
<%= link_to 'Destroy', post_path(@post),
method: :delete,
data: { confirm: 'Deseja confirmar a exclusão?' } %>

<%= link_to 'New Post', new_post_path %>
<%= link_to 'Home', home_page_index_path %>